# Generated by Django 4.0.2 on 2022-02-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_author_post_user_alter_comment_perent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='perent',
        ),
    ]
